version: '3'
services:
  zeppelin:
    image: apache/zeppelin:0.9.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeppelin
    volumes:
      - ${PWD}/notebook:/notebook
      - ${PWD}/logs:/logs
      - ${PWD}/data:/learn
      # - ${SPARK_HOME}:/spark
    environment:
      # - SPARK_HOME=/spark
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_SPARK_MAXRESULT=10000
      - ZEPPELIN_INTERPRETER_OUTPUT_LIMIT=204800
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 8080:8080
      - 4040:4040
      - 4041:4041
    networks:
      - mde
    hostname: "zeppelin"

  # Jupyter notebook
  jupyter-spark:
        hostname: myjupyter
        container_name: jupyter_container
        image: 'jupyter/pyspark-notebook:spark-3.2.0'
        networks:
            - oasiscorp
        ports:
          - "8888:8888"
        volumes:
          - ./jupyter_notebooks:/home/jovyan/work/notebooks/
          - ./spark/resources/data:/home/jovyan/work/data/
          - ./spark/resources/jars:/home/jovyan/work/jars/
          - ./spark/conf:/usr/local/spark/conf
        restart: always
        depends_on:
                - postgres

networks:
  mde:
    external:
      name: mde

