version: '3'

services:

  mysql:
    image: mysql:8.0.23
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ${PWD}/data/mysqldir:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 3306:3306
    networks:
      - mde
    hostname: mysql
  
  zeppelin:
    image: apache/zeppelin:0.9.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeppelin
    volumes:
      - ${PWD}/notebook:/notebook
      - ${PWD}/logs:/logs
      - ${PWD}/data:/learn
      # - ${SPARK_HOME}:/spark
    environment:
      # - SPARK_HOME=/spark
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_SPARK_MAXRESULT=10000
      - ZEPPELIN_INTERPRETER_OUTPUT_LIMIT=204800
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 8080:8080
      - 4040:4040
      - 4041:4041
    networks:
      - mde
    hostname: "zeppelin"


  # Jupyter Notebook - PySpark Enabled
  jupyter-spark:
        build:
            context: jupyter
        hostname: myjupyter
        container_name: jupyter_container
        networks:
            - mde
        ports:
          - "8888:8888"
        volumes:
          - ./jupyter/notebooks:/home/jovyan/work/notebooks/
          - ./spark/resources/data:/home/jovyan/work/data/
          - ./spark/resources/jars:/home/jovyan/work/jars/
          - ./spark/conf:/usr/local/spark/conf
        restart: always
        depends_on:
          - mysql


networks:
  mde:
    external:
      name: mde

